### ISSUE TITLE
Issue with Type property when fetching what I believe to be the double sided lands from the Jurassic World set

### ISSUE THREAD

**Issue by Tapervirus** [alessandrobelli/mtg-notion-importer#1]
The script seemed to be running fine (though I had to add an Illustration file & media property), but can't seem to get past what I believe to be the double sided land of the Jurassic World set. Any chance you'd be able to help with this or point me in the right direction?

Here's what it's outputting after reaching the same card each time:

Processing cards for Jurassic World Collection:  44%|████▍     | 20/45
"Traceback (most recent call last):
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\notion_client\client.py", line 118, in _parse_response
    response.raise_for_status()
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\Downloads\mtg-notion-importer-main\mtg-notion-importer-main\magic-notion.py", line 148, in update_or_create_page
    created_page = notion.pages.create(**base_page_create)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\notion_client\api_endpoints.py", line 208, in create
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\notion_client\client.py", line 194, in request
    return self._parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\notion_client\client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.properties.Type.multi_select[0].id should be defined, instead was `undefined`.
body.properties.Type.multi_select[0].name should be populated, instead was `""`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jackb\Downloads\mtg-notion-importer-main\mtg-notion-importer-main\magic-notion.py", line 408, in <module>
    import_cards()
  File "C:\Users\jackb\Downloads\mtg-notion-importer-main\mtg-notion-importer-main\magic-notion.py", line 398, in import_cards
    update_or_create_page(card)
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackb\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x16699628650 state=finished raised APIResponseError>]"

Apologies if this is not correct procedure, I am very new to this, so any assistance you could give, even to direct me to a better place to raise this is very much appreciated. Thank you!

**Comment by alessandrobelli** [comment]
Can this card have no type? That is very odd. 
I tried to fix it, but I can't test it directly now since I'm out of home. Let me know if it works!

**Comment by Tapervirus** [comment]
Thank you Alessandro for such a quick response! Those edits seem to have solved this issue, thank you so much! Your work both on the original script and the assistance are both highly appreciated!
